#!/bin/bash
set -euo pipefail

d=$(dirname -- "$( dirname -- "${BASH_SOURCE[0]}" )"  &> /dev/null && pwd )

# Set up the release URL so we can retrieve our binary
baseUrl="https://github.com/jeremybumsted/discord-buildkite-plugin/releases/download"
pluginVersion=$(git describe --tags)
os=$(uname -o)
arch=$(uname -m)
binaryUrl="${baseUrl}/${pluginVersion:-"v0.1.11"}/discord-buildkite-plugin_${os}_${arch}.tar.gz"
fileName="discord-buildkite-plugin_${os}_${arch}.tar.gz"

curl -OL "${binaryUrl}"

echo "~~~ 🔌 Preparing plugin"

tar -xf "${fileName}" -C "${d}"/hooks/ pre-exit
rm "${fileName}"

